services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: db_prueba
      PORT: 3000

  db:
    image: mysql:8.0
    restart: unless-stopped
    cap_add:
      - SYS_NICE  # Helps with MySQL performance
    environment:
      MYSQL_DATABASE: db_prueba
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'  # Allow root connections from any host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: